#! /usr/bin/env python3
import random
def get_passwd():
	pass_wd=[1,2,3,4,5,6,7,8,9,0]
	end=""
	for s in range(20):
		a = random.randint(0,len(pass_wd)-1)
		end+=str(pass_wd[a])
	print(end)
get_passwd()
