#! /usr/bin/env python3
import random
def get_passwd():
	pass_wd=[1,2,3,4,5,6,7,8,9,0,'q','w','e','r','t','y','u','i','o','p',
			'a','s','d','f','g','h','j','k','l','z','x','c','v','b','n','m',
			'Q','W','E','R','T','Y','U','I','O','P','A','S','D','F','G','H',
			'J','K','L','Z','X','C','V','B','N','M']
	end=""
	for s in range(6):
		a = random.randint(0,len(pass_wd)-1)
		end+=str(pass_wd[a])
	print(end)
get_passwd()
