#! /usr/bin/env python3
import random
import sys
import os
def main():
	gpus = sys.argv
	os.system('clear')
	var_exists = "name"
	if len(gpus)>1:
		var_exists = gpus[1]
	print("")
	print("	git add .")
	print("	git commit -m \"first commit\"")
	print("	git status")
	print("	git remote add origin git@github.com:LarryFranken/%s.git"%var_exists)
	print("	# git pull")
	print("	git push origin master")
	print("	")
	print("	the err for :更新被拒绝，因为您当前分支的最新提交落后于其对应的远程分支")
	print("	# git pull origin master")
	print("	git fetch origin    #获取远程更新")
	print("	git merge origin/master #把更新的内容合并到本地分支")
	print("")
	print("")
if __name__ =="__main__":
	main()
